### 1. 初始化数据库
POST http://127.0.0.1:9527/initdb
Content-Type: application/json

{
    "dbtype":   "mysql",
    "host":     "127.0.0.1",
    "port":     "3306",
    "username": "root",
    "password": "root1234",
    "db_name":  "test"
}

### 2. 获取数据库名
GET http://127.0.0.1:9527/autoCode/getDB
Content-Type: application/json

### 3. 获取对应数据库的表
GET http://127.0.0.1:9527/autoCode/getTables?db_name=world
Content-Type: application/json


### 4. 获取指定表所有字段信息
GET http://127.0.0.1:9527/autoCode/getColumn?db_name=demo&table_name=test
Content-Type: application/json

### 5. 预览创建代码
POST http://127.0.0.1:9527/autoCode/preview
Content-Type: application/json

{
  "struct_name":"Test",
  "table_name":"test",
  "package_name":"test",
  "abbreviation":"test",
  "description":"test表",
  "auto_create_api_to_sql":true,
  "auto_move_file":false,
  "fields":[
    {
      "field_name":"Barcode",
      "field_desc":"barcode字段",
      "field_type":"string",
      "data_type":"text",
      "field_json":"barcode",
      "data_type_long":"",
      "column_name":"barcode",
      "comment":"",
      "field_search_type":"",
      "dict_type":""
    }
  ],
  "hump_package_name":"test"
}